#!/usr/bin/env sh

changedFiles="$(git diff-tree -r --name-only --no-commit-id $1 $2)"
[ -z "$changedFiles" ] && exit 0

echo "$changedFiles" | tr -d '\r' | xargs node scripts/notify-lockfile-changed.js
